name = "response-page"
main = "src/index.ts"
compatibility_date = "2023-11-08"

[env.production]
workers_dev = false
routes = [
	{ pattern = "response.page", custom_domain = true, zone_name = "response.page" }
]

[site]
bucket = "./docs"
